### ISSUE TITLE
GHC cannot build some packages, perhaps need update

### ISSUE THREAD

**Issue by dfordivam** [WebGHC/wasm-cross#22]
Cannot compile with webghc, 8.6.1 works fine.
should we merge stuff from 8.6.1 branch? 

```
Building library for transformers-compat-0.6.2..
[1 of 4] Compiling Control.Monad.Trans.Instances ( src/Control/Monad/Trans/Instances.hs, dist/build/Control/Monad/Trans/Instances.o )
src/Control/Monad/Trans/Instances.hs:536:10: error:
    Duplicate instance declarations:
      instance forall k a (b :: k).
               Semigroup a =>
               Semigroup (Constant a b)
        -- Defined at src/Control/Monad/Trans/Instances.hs:536:10
      instance [safe] forall k a (b :: k).
                      Semigroup a =>
                      Semigroup (Constant a b)
        -- Defined in ‘Data.Functor.Constant’
    |
536 | instance (Semigroup.Semigroup a) => Semigroup.Semigroup (Constant a b) where
    |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by dfordivam** [comment]
I guess this is a blocking issue, as basic stuff like `lens` depends on it..

**Comment by ElvishJerricco** [comment]
Hm. I was able to build `transformers-compat` just fine. When hydra finishes building the new GHC build, give it a try with `nix-build -A nixpkgsWasm.haskell.packages.ghcHEAD.transformers-compat`.

**Comment by dfordivam** [comment]
I think I made some mistake.. cannot reproduce this one. I am doing all stuff in cabal setup, so things get a bit messy.

How about this one .. semigroupoids-5.3.1

```
[16 of 21] Compiling Data.Semigroup.Foldable.Class ( src/Data/Semigroup/Foldable/Class.hs, /home/divam/nobup/tmpcabalstuff/dist-newstyle/build/wasm32-unknown-wasm/ghc-8.5.20180424/semigroupoids-5.3.1/build/Data/Semigroup/Foldable/Class.o )
src/Data/Semigroup/Foldable/Class.hs:94:10: error:
    • Could not deduce (Foldable (Alt f))
        arising from the superclasses of an instance declaration
      from the context: Foldable1 f
        bound by the instance declaration
        at src/Data/Semigroup/Foldable/Class.hs:94:10-48
    • In the instance declaration for ‘Foldable1 (Alt f)’
   |
94 | instance Foldable1 f => Foldable1 (Monoid.Alt f) where
   |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by ElvishJerricco** [comment]
`semigroupoids-5.2.2` built fine for me, but that's older than what you're trying.

**Comment by dfordivam** [comment]
Not an issue..
